### ISSUE TITLE
Any ideas on why it doesn't work on a ESP32?

### ISSUE THREAD

**Issue by MacGyverr** [ldab/u-blox_GNSS#3]
I get this reply:
Here you are, lon:306.7161255 lat:47.0966301
calculated error: 9.49m

Or try the following link to see on google maps:
https://www.google.com/maps/search/?api=1&query=47.0966301,306.7161255

The latitude is spot on, the longitude, not so much.

I'm using Serial2 (ping 16 and 17 on my ESP32) and have modified the sketch as such "#define Serial_GNSS Serial2"
Any idea on why the longitude is wonky? 
If I had to guess, I'd say it was the fact my longitude is a negative number and you've used float and are shifting things and because my cpu is 32-bit it's screwing with the negative part.
I'll try to teach myself how to shift things around in a 32-bit environment, but I don't have a lot of hope.

**Comment by MacGyverr** [comment]
Here is a full debug with me also outputting the 3 elements you use to derive longitude (res[30-32]):



Start GNSS Configuration
UBX-CFG-PRT -> Disable NMEA and enable UBX
55
14
0
6
0
2
1
5
98
181
CRC =  1
UBX-CFG-CFG -> Saving configuration
64
23
9
6
0
2
1
5
98
181
CRC =  1
UBX-CFG-PSM -> Power save mode ON/OFF
189
148
134
6
0
2
1
5
98
181
CRC =  1
UBX-CFG-PS2 -> Configure search time
114
73
59
6
0
2
1
5
98
181
CRC =  1
UBX-CFG-CFG -> Saving configuration
64
23
9
6
0
2
1
5
98
181
CRC =  1

GNSS initialized.
Get location
UBX-NAV-PVT -> Pooling coordinates
0
7
1
98
181

res[32]:  188 res[31]:  63  res[30]:  251

lon:  427.37 lat:  2.24  -  13  ~ 4273750.00 m
251
20
7
7
229
11
165
219
120
0
92
7
1
98
181

res[32]:  188 res[31]:  63  res[30]:  251

lon:  427.37 lat:  2.24  -  13  ~ 4273750.00 m
92
7
1
98
181

res[32]:  188 res[31]:  63  res[30]:  251

lon:  427.37 lat:  2.24  -  13  ~ 4273750.00 m
0
47
16
6
20
7
7
229
11
165
242
232
0
92
7
1
98
181

res[32]:  188 res[31]:  63  res[30]:  251

lon:  427.37 lat:  2.24  -  13  ~ 4273750.00 m
181

res[32]:  188 res[31]:  63  res[30]:  251

lon:  427.37 lat:  2.24  -  13  ~ 4273750.00 m
92
92
164
0
0
0
0
0
0
0
0
0
35
74
224
0
0
2
210
0
74
250
170
0
0
102
77
0
0
0
0
0
0
18
25
0
0
0
0
255
255
238
224
0
0
5
218
0
1
242
131
0
5
28
178
0
1
89
242
0
1
13
141
28
18
81
99
182
209
130
165
3
6
8
2
29
209
62
151
0
0
1
108
55
52
16
6
20
7
7
229
11
166
8
100
0
92
7
1
98
181

res[32]:  209 res[31]:  130  res[30]:  165

lon:  306.72 lat:  47.10  -  2  ~ 335.03 m
242
255
241
185
249
28
18
89
108
182
207
139
34
6
6
8
3
0
3
237
24
0
0
2
8
55
56
16
6
20
7
7
229
11
166
22
16
0
92
7
1
98
181

res[32]:  207 res[31]:  139  res[30]:  34

lon:  306.71 lat:  47.10  -  3  ~ 335.03 m
1
98
121
255
247
22
16
28
18
103
230
182
208
27
6
7
6
8
3
0
3
237
13
0
0
1
75
55
59
16
6
20
7
7
229
11
166
33
200
0
92
7
1
98
181

res[32]:  208 res[31]:  27  res[30]:  6

lon:  306.71 lat:  47.10  -  3  ~ 335.03 m
0
255
76
13
0
0
167
38
0
0
5
120
0
1
103
248
0
1
34
234
255
250
105
218
255
250
29
115
28
18
104
83
182
208
115
37
5
6
8
3
0
3
239
68
0
0
0
253
55
2
17
6
20
7
7
229
11
166
45
128
0
92
7
1
98
181

res[32]:  208 res[31]:  115  res[30]:  37

lon:  306.71 lat:  47.10  -  3  ~ 74.47 m
25
255
255
71
253
0
0
158
201
0
0
7
179
0
1
86
1
0
1
22
236
255
253
12
166
255
252
192
64
28
18
105
78
182
208
190
141
7
6
8
3
0
3
241
236
0
0
0
243
55
5
17
6
20
7
7
229
11
166
57
56
0
92
7
1
98
181

res[32]:  208 res[31]:  190  res[30]:  141

lon:  306.71 lat:  47.10  -  3  ~ 71.40 m
92
121
49
0
0
0
0
0
0
0
0
0
35
74
224
0
0
1
254
0
11
228
226
0
0
28
8
0
146
98
189
0
0
72
184
255
255
146
65
0
0
72
85
255
255
248
123
0
0
253
59
0
0
198
31
255
253
194
176
255
253
118
73
28
18
102
58
182
208
211
60
6
10
9
3
0
3
246
73
0
0
0
179
55
8
17
6
20
7
7
229
11
166
68
240
0
92
7
1
98
181

res[32]:  208 res[31]:  211  res[30]:  60

lon:  306.71 lat:  47.10  -  3  ~ 50.72 m
92
169
2
0
0
0
0
0
0
0
0
0
35
74
224
0
0
1
254
0
19
139
164
0
0
21
56
0
147
150
127
0
0
44
165
255
255
178
66
0
0
44
87
255
255
250
198
0
0
224
227
0
0
172
142
255
254
124
128
255
254
48
26
28
18
101
105
182
208
229
20
6
10
9
3
0
3
250
159
0
0
0
158
55
11
17
6
20
7
7
229
11
166
80
168
0
92
7
1
98
181

res[32]:  208 res[31]:  229  res[30]:  20

lon:  306.71 lat:  47.10  -  3  ~ 44.17 m
CRC =  1

Here you are, lon:306.7143555 lat:47.0967636
calculated error: 44.17m

Or try the following link to see on google maps:
https://www.google.com/maps/search/?api=1&query=47.0967636,306.7143555

**Comment by ldab** [comment]
> not so much.

Can you please elabrate that? How much is not so much?

> outputting the 3 elements you use to derive longitude (res[30-32]):

There is 4 elements to derive the longitude: https://github.com/ldab/u-blox_GNSS/blob/8ce660b4c40312b3b3ec33e7f8ef45d8da074cbe/src/ublox_GNSS.cpp#L236

Can you please the 4 elements? If you find your location sensitive to share, please offset it.

**Comment by MacGyverr** [comment]
Sorry, I forgot the 4th, it's 182.
res[33]: 182 res[32]: 208 res[31]: 229 res[30]: 20
I checked the shifting and if I do the math manually outside of an ESP32 one at a time it checks out fine and spits out the proper longitude, it's some kind of quirk with the way a 32-bit CPU does it.  I barely can compile things, but I think it has to do with this statement I found online somewhere:
"On a 32-bit CPU, the registers and data bus are 32 bits wide, and a uint8_t is stored in a 32-bit variable for efficient access, so it won’t overflow if you shift them to the right."
So if I'm guessing correctly, that line (236) is taking 4 numbers in a row that are 8-bit, and trying to shift those four 8-bits all left but because each is actually now held in 32-bits that when it's a negative number it isn't working correctly because the 2s compliment is now 24 bits further to the left than before for each, so I'll have to change it to shifting each over by 8 individually and adding them together? Sorry if I'm using the nomenclature incorrectly I have no proper training in programming. 
Thanks by the way for making this library, I have tried at least 5 others and yours is the closest to just simply working. And it does it with so much less code that I can almost understand it.

Maybe I'll try ` lon = (uint32_t)(((uint32_t)res[33] << 24) + ((uint32_t)res[32] << 16) + ((uint32_t)res[31] << 8) + (uint32_t)res[30]) * 0.0000001f;` when I'm back at home and see if that works. (EDIT: it doesn't)

**Comment by ldab** [comment]
The bitwise operation probably does not work with negative numbers on the current implementation, it is an easy fix.

I will try to fix it this week.

**Comment by ldab** [comment]
That is weird, when I manually replace `res` by `{20, 229, 208, 182}`, i get, can you please confirm if that is correct:

```
Here you are, lon:-122.7823868 lat:47.0999985
calculated error: 44.17m

Or try the following link to see on google maps:
https://www.google.com/maps/search/?api=1&query=47.0999985,-122.7823868
```

**Comment by MacGyverr** [comment]
I get the same if I do it manually, but something about how a 32-bit Arduino holds all 8-bit numbers in 32-bit memory spaces makes bit-shifting for negative numbers not work correctly. And because res[] is setup as a uint8_t, the number isn't getting shifted left enough to make the negative numbers work 10000000 00000000 00000000 00000000 (negative 32bit) vs 10000000 (negative 8bit) for negative numbers that use 2s compliment to make them negative. I think I'll try assigning the res[30-33] variables into new uint16_t declared variables and then bit-shift them.  Your bit-shifting function works perfectly, just not when the numbers it expects to be in 8-bit memory locations are actually 32-bit, I think, I have no proper training.  Could be something about negative floats in a 32-bit environment, like I said, I barely know enough to get things to compile half the time.

**Comment by ldab** [comment]
What arduino version are you suing?

**Comment by MacGyverr** [comment]
My IDE is 1.89, and the module is an ESP32, the GPS is a SAM-M8Q GPS QMC5883L.
If I compile this:
`lon = (uint32_t)((182 << 24) + (208 << 16) + (229 << 8) + 20) * 0.0000001f;`

I get this:
`Here you are, lon:306.7143555 lat:47.0971031
calculated error: 48.22m
`


If I run this:
  uint8_t lon1 = 182;
  uint8_t lon2 = 208;
  uint8_t lon3 = 229;
  uint8_t lon4 = 20;
Serial.println((uint8_t)(lon1 << 24));
Serial.println((uint8_t)(lon2 << 16));
Serial.println((uint8_t)(lon3 << 8));
Serial.println((uint8_t)lon4);

I get this:
0
0
0
20


This:
  uint8_t lon1 = 182;
  uint8_t lon2 = 208;
  uint8_t lon3 = 229;
  uint8_t lon4 = 20;
Serial.println((uint16_t)(lon1 << 24));
Serial.println((uint16_t)(lon2 << 16));
Serial.println((uint16_t)(lon3 << 8));
Serial.println((uint16_t)lon4);

Outputs this:
0
0
58624
20


And lastly this:
  uint8_t lon1 = 182;
  uint8_t lon2 = 208;
  uint8_t lon3 = 229;
  uint8_t lon4 = 20;
Serial.println((uint32_t)(lon1 << 24));
Serial.println((uint32_t)(lon2 << 16));
Serial.println((uint32_t)(lon3 << 8));
Serial.println((uint32_t)lon4);



Spits out this:
3053453312
13631488
58624
20

**Comment by MacGyverr** [comment]
So after trying everything (because I have no idea what I'm doing), this works:
  uint8_t lon1 = res[33];
  uint8_t lon2 = res[32];
  uint8_t lon3 = res[31];
  uint8_t lon4 = res[30];
  int lon1a = (lon1 << 24);
  int lon2a = (lon2 << 16);
  int lon3a = (lon3 << 8);
  int lon4a = (lon4);
  lon = (lon1a + lon2a + lon3a + lon4a) * 0.0000001f;

And spits out this:
Here you are, lon:-122.7823868 lat:47.0999985
calculated error: 46.75m


Maybe you know why, I don't.

**Comment by ldab** [comment]
Please confirm your Arduino (ESP32) version, not the IDE.

>  lon = (uint32_t)((182 << 24) + (208 << 16) + (229 << 8) + 20) * 0.0000001f;

this is wrong.

**Comment by MacGyverr** [comment]
If you mean the model it's this:
ESP-32S ESP32 Development Board

If you mean the board manager it's this. esp32-1.0.6
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

If you mean something else, please elaborate.
![71SyCCoTfML _AC_SL1000_](https://user-images.githubusercontent.com/6500800/126596450-5dcb107f-2b2b-4d6d-a3ee-2dfebfa8e6dc.jpg)
![ESP32-30PIN-DEVBOARD](https://user-images.githubusercontent.com/6500800/126596474-9700399e-5600-42c7-8027-e3d2a9737214.png)

**Comment by ldab** [comment]
> If you mean the board manager it's this. esp32-1.0.6

Yes, this one. It is the same I have tested.

I'm unable to reproduce your problem and can't help, sorry. If you want to try what I tried, include the following lines, [here](https://github.com/ldab/u-blox_GNSS/blob/8ce660b4c40312b3b3ec33e7f8ef45d8da074cbe/src/ublox_GNSS.cpp#L235):
```
res[30] = 20;
res[31] = 229;
res[32] = 208;
res[33] = 182;
```
