### ISSUE TITLE
Groundspeed data

### ISSUE THREAD

**Issue by chron0** [ldab/u-blox_GNSS#4]
Hi, thank you very much for sharing this lib. I am currently working on a low power tracking application as well and would like to use your lib for it. The only thing I seem to be missing is how to get groundspeed data out of it. 

I guess buried somewhere in res?

https://github.com/ldab/u-blox_GNSS/blob/8ce660b4c40312b3b3ec33e7f8ef45d8da074cbe/src/ublox_GNSS.cpp#L225

**Comment by ldab** [comment]
It is not buried, it is only not parsed, please refer to UBX-NAV-PVT https://content.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_UBX-13003221.pdf

You can include something like the following on the line below:
```
gSpeed = (float)((res[69] << 24) + (res[68] << 16) + (res[67] << 8) + res[66] ) / 1000.0f;
```

https://github.com/ldab/u-blox_GNSS/blob/8ce660b4c40312b3b3ec33e7f8ef45d8da074cbe/src/ublox_GNSS.cpp#L240

**Comment by chron0** [comment]
Perfect! thx so much for the quick hint <3

```
[  8109][D][tbeam.cpp:263] GPS_Init(): Calculated error: 33.20 m
[  8112][D][tbeam.cpp:264] GPS_Init(): Groundspeed: 0.7 kmh
```

Works.
